export const env = {
  NODE_ENV: process.env.NODE_ENV ?? "development",
  DATABASE_URL: process.env.DATABASE_URL!,
  REDIS_URL: process.env.REDIS_URL ?? "redis://localhost:6379",
  GEMINI_API_KEY: process.env.GEMINI_API_KEY!,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID!,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY!,
  AWS_REGION: process.env.AWS_REGION ?? "auto",
  R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID!,
  R2_BUCKET: process.env.R2_BUCKET ?? "tradehubuae-media",
  R2_PUBLIC_URL: process.env.R2_PUBLIC_URL!,
  STORAGE_ENDPOINT: process.env.STORAGE_ENDPOINT!,
  STORAGE_PROVIDER: (process.env.STORAGE_PROVIDER ?? "r2") as "r2" | "s3",
  RESEND_API_KEY: process.env.RESEND_API_KEY!,
  EMAIL_FROM: process.env.EMAIL_FROM ?? "TradeHub UAE <orders@tradehubuae.com>",
  JWT_SECRET: process.env.JWT_SECRET!,
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN ?? "7d",
  API_PORT: Number(process.env.API_PORT ?? 4000),
  API_HOST: process.env.API_HOST ?? "0.0.0.0",
  CORS_ORIGIN: (process.env.CORS_ORIGIN ?? "http://localhost:3000").split(","),
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000",
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  NEXT_PUBLIC_ADMIN_URL: process.env.NEXT_PUBLIC_ADMIN_URL ?? "http://localhost:3001",
  DEFAULT_CURRENCY: process.env.DEFAULT_CURRENCY ?? "AED",
  DEFAULT_LOCALE: process.env.DEFAULT_LOCALE ?? "en-AE",
  SITE_NAME: process.env.SITE_NAME ?? "TradeHub UAE",
  SITE_DESCRIPTION:
    process.env.SITE_DESCRIPTION ??
    "UAE's Premier Destination for IT Equipment - New & Refurbished Laptops, PCs, Components",
  SITE_URL: process.env.SITE_URL ?? "https://tradehubuae.com",
  BULL_PREFIX: process.env.BULL_PREFIX ?? "tradehub",
  BULL_DEFAULT_JOBS: Number(process.env.BULL_DEFAULT_JOBS ?? 5),
  FEATURE_AI_PRODUCT_GENERATION: process.env.FEATURE_AI_PRODUCT_GENERATION !== "false",
  FEATURE_BULK_SALES: process.env.FEATURE_BULK_SALES !== "false",
  FEATURE_COMBO_OFFERS: process.env.FEATURE_COMBO_OFFERS !== "false",
  FEATURE_COMPARE_PRODUCTS: process.env.FEATURE_COMPARE_PRODUCTS !== "false",
  FEATURE_WISHLIST: process.env.FEATURE_WISHLIST !== "false",
  COD_ENABLED: process.env.COD_ENABLED !== "false",
  CARD_ENABLED: process.env.CARD_ENABLED === "true",
} as const;
